Makefile:
	If is set of rules used to upadate existing and creat new files or run some commands depending upon last modification time of the source files.
	General make file syntax looks like

target : prerequisite
	recipe

	prerequisite could be nothing. While target could be name of action(phony action) rather than output file.
	recipe is rule for updation.

	recipe could be one of more, specified on same line with ';' or multiple lines  with '\ ' at the end
	.RECIPEPREFIX is character that must appear before each recipe.
	Default make file is makefile or Makefile , you could specify with -f option

2.3 How to process a default Goal:

	Make file starts with first goal in file, which could be overided with option on command line or .DEFAULT_GOAL variable.
	Make file only updates target with recipe rule, when source file is recent than object file. To build target all its prerequisites must be updated.

2.4 Variables:
	you could forget files to add and remove from all places in all recipes. To simplify we could collect all files under one variable.
	objects = a.o b.o \
		c.o
	target : $(objects)	
			edit -o edit $(objects)
	
2.5 Implicit Rules:
	Make file has some implicit rules
	a.o: a.h will compile a.c to result into a.o, with cc. So even if u do not provide any recipe it has basic recipe of cc -c a.o a.c


3.1 Makefile contents
	a> explicit rules to make target
	b> implicit rules to make target files having certain type
	c> directives: 
			to compile certain part depending upon some condition
			include some file
			Defining a variable from a verbatim string containing multiple lines
	d> variables
	e> comments with #

3.2 Spliting line wiht \, white spaces before \ and at the begening of new line are convertd into single space if it is not POSIX makefile(.POSIX).

    Makefile name:
	default name for make file is makefile, Makefile and GNUmakefile. Makefile is preferred because it appears first.
	You could specify other makefile name by -f or --file commandline option, then default makefiles are ignored.

3.3 Including other files
	Other make files could be included in make files
	a> when you have common enviromental variables for multiple make files, create a makefile with env varibles and include it in all makefiles
	b> when you want pre-requisites names in one make file, rather than traditional method of appending prerequisite rules at the end of main makefile

	It could be done with
	include fileToBeIncluded
	e.g include foo *.mk 
	a> *.mk will expand
	b> it searches for included files in
		- current dir
		- dir provided with -I or --include-dir as option to make
		- some dirs /usr/include/ /usr/gnu/include /usr/local/include
		
	if some included makefile is not present only warning message is generated.
	to avoide this warning use -include or sinclude instead of include
	

